### ISSUE TITLE
Hilt integration doesn't support Screen classes

### ISSUE THREAD

**Issue by xinkev** [adrielcafe/voyager#15]
I don't if that is intentional.Hilt integration only works with `AndroidScreen`. 
Also, docs seems incomplete... There is a sample project for that though.

**Comment by isshindev** [comment]
Sorry. I didn't know about that. I was only using `Screen` all along. Now that I think about it, it's true that hilt works with Android only. Then, documentation seems a little miss leading since `Screen` was used in the examples. 

Here's one thing I'm really curious though. You said Android context is only provided by `AndroidScreen`. But we can get also get it inside any Composable functions with `LocalContext.current`. So, what's the different?

Thanks!

**Comment by programadorthi** [comment]
Hi guys, there was a misunderstood here. I was thinking that we were talking about Androidx ViewModel. There is no need to Hilt and ScreenModel be exclusive to AndroidScreen really. It was a mistake because first purpose was to create an integration with Androix ViewModel.
We have fixed here #18

**Comment by adrielcafe** [comment]
Fixed on [1.0.0-beta13](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-beta13), feel free to reopen if the issue persists.
