### ISSUE TITLE
how to inject inside compose in commonMain using koin 

### ISSUE THREAD

**Issue by aplha98** [adrielcafe/voyager#201]
[1.0.0-rc07](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-rc07) Pre-release
Add Compose Multiplatform support to voyager-koin (https://github.com/adrielcafe/voyager/pull/159) by @geworfener

how to use koin inside compose

**Comment by CompileConnected** [comment]
i don't think the voyage-koin support "normal" koin implementation, 
voyager-koin just support the factory for the screen.
so on kmm using koin will not support lazy initialization.
but there's work around that i create, which sorta work.

i'm using moco for the viewmodel and kmm compose
you can check in here, I include all necessity so you can use koin on voyager screen

https://gist.github.com/CompileConnected/57a3f504c04e277afdf071eed53a6999

**Comment by CompileConnected** [comment]
or you can pass it all to the screen,
```
//example screen
HomeScreenModel(val viewmodel: VM, val otherViewModel: VM): ScreenModel

//how to inject it
module {
    factory { HomeScreenModel(get(), get()) } 
}
```

which i think should work, might be. don't know is it work on kmm

**Comment by DevSrSouza** [comment]
The Voyager Koin extension is only for retrieving ScreenModel from the DI and hold it instance until the Screen leave the compostion, there is nothing specific about Koin instead of that. Using Koin + Compose is a question for [repository](https://github.com/InsertKoinIO/koin) I think.

If I did understand correctly, if not, feel free to reopen the issue if it is a question of how to use ScreenModel.
