### ISSUE TITLE
ScreenModel function goes into infinite loop when calling from screen

### ISSUE THREAD

**Issue by imneeraj** [adrielcafe/voyager#470]
I'm trying to make an api call from screen.

but the moment i call ScreenModel function , system goes into infinite loop.
what is the best way to call api , or pass parameter to ScreenModel.

i cannot directly pass param in ScreenModel constructer as i'm using koin DI

<img width="760" alt="Screenshot 2024-08-11 at 1 59 15 AM" src="https://github.com/user-attachments/assets/f1d92829-0603-4f77-b010-f7cc2de874b9">

**Comment by Syer10** [comment]
Please read https://developer.android.com/develop/ui/compose/mental-model and https://developer.android.com/develop/ui/compose/side-effects

You likely need to understand compose principles better before continuing, since you are not thinking about composables properly. Composables a repeatable functions that draw the screen, no state management should be happening on UI draws.

**Comment by imneeraj** [comment]
thank you @Syer10 , 
i understand. i need to change my approach .
