### ISSUE TITLE
Does ability to navigation not from composable function?

### ISSUE THREAD

**Issue by Anton111111** [adrielcafe/voyager#60]
I wonder is has ability to navigate not from Composable? For example if i want navigate from viewModel or UseCase class. 
How i see that i can get  navigator instance with LocalNavigator.currentOrThrow only from Composable function.

**Comment by adrielcafe** [comment]
The navigation relies on state changes to work, you don't have to be inside a composition. So, you can create an instance of your ViewModel/UseCase inside the composition and pass the navigator instance to it. 

Example with Koin:
```
val navigator = LocalNavigator.currentOrThrow
val viewModel = getViewModel<MyViewModel>(navigator)
```

Since we can have nested navigators (thanks to CompositionLocals) I don't see a way to get the navigator instance outside the composition.

**Comment by Anton111111** [comment]
Thanks
