### ISSUE TITLE
Allow disabling state restoration

### ISSUE THREAD

**Issue by natanfudge** [adrielcafe/voyager#63]
I have cases where state restoration is either not desirable or not worth implementing the serialization for. Please provide a way to disable state restoration, either globally through `Navigator` or on a per-screen basis through `Screen`. If the app is closed from a screen that is not restorable it should use the initial screen on startup.

**Comment by kevinvanmierlo** [comment]
I'd also like to be able to disable this. I usually set the configChanges to handle myself. With Compose this is easy to do and most stuff where you need state restoration for are nog longer needed.

Since it's been a year since this is asked. If I have the time I'll try to make a pull request. I've looked at the code and I think a per-screen basis is hard to do. So globally is probably easier. I thought of a few options. One is a global config in which you just say true or false to state restoration. Another option would be to create a SaveableNavigator and a Navigator (which wouldn't be saveable). Another would be to pass a parameter with the Navigator that says it will be saveable. 

Personally I like the option of the SaveableNavigator, but this would require change to many code bases. So the last option with a parameter or a config will make the most sense for now. What do you think? 

Also the Screen will still be Serializable, as long as you don't use it to serialize it you should be fine, but that can be hard to understand. This is also a reason why I don't want the state restoration, because you don't know you messed up until you move the app to the background in the screen you make the mistake.

**Comment by DevSrSouza** [comment]
We have updated state restoration docs, have a look to see if now it can help you.
https://voyager.adriel.cafe/state-restoration

We also added on Voyager 1.0.0-rc05 a new API for customizing NavigatorSaver, you can disable it easily by writing or own NavigatorSaver like:

```kotlin
public fun disableNavigatorSaver(): NavigatorSaver<Any> = NavigatorSaver { initialScreens, stateHolder, disposeBehavior, parent ->
    Saver(
        save = { "" },
        restore = {
            Navigator(initialScreens, stateHolder, disposeBehavior, parent)
        }
    )
}

CompositionLocalProvider(
    LocalNavigatorSaver provides disableNavigatorSaver()
) {
    Navigator(...) {
       ...
    }
}
```

**Comment by kevinvanmierlo** [comment]
@DevSrSouza That's awesome! However I think this Navigator constructor is internal. So this specific code can't be used. But if I set the restore to null it also works, not sure if it's okay to return null though?

**Comment by DevSrSouza** [comment]
I see... I will take a look for the next release in this case.

**Comment by DevSrSouza** [comment]
Hi @kevinvanmierlo, with [1.0.0-rc06](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-rc06) you can do it!

**Comment by kevinvanmierlo** [comment]
Awesome @DevSrSouza , thanks!

**Comment by kevinvanmierlo** [comment]
Just wanted to add something to this thread for people like me who want to pass all sorts of objects to screens without having to think about the Serializable. If you disable the navigatorSaver the tabbar navigator and inner navigators will not work as well. So I created this to counter that:

```
object KMNavigatorSaver {
    val saverMap = mutableMapOf<String, List<Screen>>()
}

@OptIn(ExperimentalVoyagerApi::class, InternalVoyagerApi::class)
public fun kmNavigatorSaver(): NavigatorSaver<String> = NavigatorSaver { initialScreens, key, stateHolder, disposeBehavior, parent ->
    Saver(
        save = {
            val uuid = randomUUID() // This is my multiplatform implementation, use Androids implementation here if you only use Android
            KMNavigatorSaver.saverMap[uuid] = it.items
            uuid
        },
        restore = {
            val items = KMNavigatorSaver.saverMap[it]
            KMNavigatorSaver.saverMap.remove(it) // Remove so we don't keep everything in memory all the time
            Navigator(items ?: initialScreens, key, stateHolder, disposeBehavior, parent)
        }
    )
}
```

This will make sure the inner navigators will continue to work. However when the system closes your app and saves everything, the screens will be gone when the app is restored.
