### ISSUE TITLE
Last ScreenLifecycleOwner is applied to all screens in a ScreenTransition

### ISSUE THREAD

**Issue by dandc87** [adrielcafe/voyager#79]
We noticed that ViewModels were being recreated as we navigated away from a screen (and in our case causing occasional crashes)

I believe it's because the latest screen's `ScreenLifecycleOwner` is applied to all of the contents of `Navigator()` and not to individual screens inside `ScreenTransition` (or in `CurrentScreen()`)

https://github.com/adrielcafe/voyager/blob/0db2c7904f350f252c82a6c644216767989b9cd1/voyager-navigator/src/commonMain/kotlin/cafe/adriel/voyager/navigator/Navigator.kt#L73

I'd be happy contribute a PR if this is the correct fix 😄

**Comment by beyondeye** [comment]
Hi  I have just published a fork of voyager with **bug fixes** and **new features** [here](https://github.com/beyondeye/compose_bloc).
I have that this specific issue of yours has been solved in my fork. I have changed the way screen lifecycle is managed, because of this kind of issue
I will be happy to have your feedback.
